name: Automation Framework CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:  # manual trigger

jobs:

  # =========================
  # Job 1: Run API Tests
  # =========================
  api-tests:
    runs-on: ubuntu-latest

    env:
      DB_HOST: localhost
      DB_PORT: 3306
      DB_NAME: automation_tests
      DB_USER: root
      DB_PASS: Ck@709136  # use GitHub Secrets for security

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: Ck@709136
          MYSQL_DATABASE: automation_tests
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # Step 1: Checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Java
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 23

      # Step 3: Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build project (skip tests)
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # Step 5: Run API tests only
      - name: Run API Tests
        run: mvn test -Dtest=**/*JsonPlaceholderTests.java

      # Step 6: Upload artifacts
      - name: Upload API Test Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: api-test-reports
          path: |
            artifacts/html/*
            artifacts/csv/*
            artifacts/excel/*
            artifacts/j-unit/*
            artifacts/logs/*

  # =========================
  # Job 2: Run UI Tests
  # =========================
  ui-tests:
    runs-on: ubuntu-latest
    needs: api-tests  # optional, run after API tests

    env:
      DB_HOST: localhost
      DB_PORT: 3306
      DB_NAME: automation_tests
      DB_USER: root
      DB_PASS: Ck@709136

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: Ck@709136
          MYSQL_DATABASE: automation_tests
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 23

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install -DskipTests

      # Run UI tests only
      - name: Run UI Tests
        run: mvn test -Dtest=**/*BlazeDemoTests.java

      # Upload UI test artifacts
      - name: Upload UI Test Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ui-test-reports
          path: |
            artifacts/html/*
            artifacts/csv/*
            artifacts/excel/*
            artifacts/j-unit/*
            artifacts/screenshots/*
            artifacts/logs/*
