name: Automation Framework CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:  # manual trigger

jobs:

  # =========================
  # Job 1: Run API Tests
  # =========================
  api-tests:
    runs-on: ubuntu-latest

    env:
      DB_HOST: localhost
      DB_PORT: 3306
      DB_NAME: automation_tests
      DB_USER: root
      DB_PASS: Ck@709136  # consider using GitHub Secrets

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: Ck@709136
          MYSQL_DATABASE: automation_tests
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 23

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run API Tests
        run: mvn test -Dtest=**/*JsonPlaceholderTests.java

      - name: Upload API Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: api-test-reports
          path: |
            artifacts/html/*
            artifacts/csv/*
            artifacts/excel/*
            artifacts/j-unit/*
            artifacts/logs/*

  # =========================
  # Job 2: Run UI Tests
  # =========================
  ui-tests:
    runs-on: ubuntu-latest

    env:
      DB_HOST: localhost
      DB_PORT: 3306
      DB_NAME: automation_tests
      DB_USER: root
      DB_PASS: Ck@709136

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: Ck@709136
          MYSQL_DATABASE: automation_tests
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 23

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run UI Tests
        run: mvn test -Dtest=**/*BlazeDemoTests.java

      - name: Upload UI Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-reports
          path: |
            artifacts/html/*
            artifacts/csv/*
            artifacts/excel/*
            artifacts/j-unit/*
            artifacts/screenshots/*
            artifacts/logs/*
