name: Full Regression Suite

on:
  push:
    branches:
      - main
      - master
  schedule:
    # Nightly at 2:00 AM IST (~20:30 UTC previous day)
    - cron: "30 20 * * *"

jobs:
  regression-tests:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Java (match your local version)
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3️⃣ Install Chrome & WebDriver
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          google-chrome --version

      - name: Install ChromeDriver
        run: |
          sudo apt-get install -y chromium-chromedriver
          chromedriver --version

      # 4️⃣ Setup MySQL (optional — only if your tests require DB)
      - name: Start MySQL Service
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '8.0'
          mysql database: 'automation_tests'
          mysql user: 'root'
          mysql password: ${{ secrets.MYSQL_PASSWORD }}

      # 5️⃣ Cache Maven dependencies for faster builds
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      # 6️⃣ Build & Run Tests (Parallel)
      - name: Run UI & API Tests
        run: mvn clean test -Dsurefire.parallel=classes -Dsurefire.threadCount=10

      # 7️⃣ Upload HTML Reports & Screenshots as artifacts
      - name: Upload HTML Reports
        uses: actions/upload-artifact@v4
        with:
          name: html-reports
          path: artifacts/reports/**/*.html

      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: artifacts/screenshots/

      # 8️⃣ (Optional) Notify Analytics Endpoint
      - name: Refresh Analytics
        if: always()
        run: |
          curl -X POST https://your-analytics-endpoint.com/api/refresh \
            -H "Content-Type: application/json" \
            -d '{"triggered_by": "github_actions"}'
