name: Full Regression

on:
  push:
  schedule:
    - cron: '0 1 * * *' # nightly at 01:00 UTC

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: automation_tests
          MYSQL_USER: ci
          MYSQL_PASSWORD: ci
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      DB_URL: jdbc:mysql://localhost:3306/automation_tests
      DB_USER: ci
      DB_PASS: ci

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '23'

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Build & Run Tests
        run: mvn -B test -DskipTests=false

      - name: Collect artifacts (reports/screenshots)
        uses: actions/upload-artifact@v4
        with:
          name: automation-artifacts
          path: |
            artifacts/html-report/**
            artifacts/screenshots/**
            target/surefire-reports/**

      - name: Call analytics refresh endpoint
        run: |
          curl -X POST "http://localhost:8080/analytics/refresh" || true
