name: Full Regression Suite

on:
  push:
    branches:
      - master
  schedule:
    # Runs every night at 2:00 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  regression-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [17]
    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Setup Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}

      # Cache Maven packages
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Run tests in parallel
      - name: Run UI and API Tests
        run: mvn clean test -Dsurefire.parallel=classes -Dsurefire.threadCount=10

      # Upload HTML reports
      - name: Upload HTML Reports
        uses: actions/upload-artifact@v3
        with:
          name: html-reports
          path: artifacts/html/*.html

      # Upload screenshots
      - name: Upload Screenshots
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: artifacts/screenshots/*.png

      # Optional: Call analytics endpoint (using JSONPlaceholder as placeholder)
      - name: Refresh Analytics
        run: |
          curl -X POST https://jsonplaceholder.typicode.com/posts \
               -H "Content-Type: application/json" \
               -d '{"triggered_by": "github_actions"}'
