#-------------------------------------------------------------------------------#
# Full CI Pipeline: Qodana + Regression Tests + Reports + Analytics
#-------------------------------------------------------------------------------#

name: Full CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
  schedule:
    - cron: '0 2 * * *' # nightly at 2:00 AM UTC
  workflow_dispatch:

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [17]

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Setup Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}

      # Step 3: Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Run Qodana Code Quality Scan
      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2025.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          pr-mode: false
          use-caches: true
          post-pr-comment: true
          use-annotations: true
          upload-result: true
          push-fixes: 'none'
          output-path: qodana-results

      # Step 5: Upload Qodana SARIF for GitHub Code Scanning
      - name: Upload Qodana SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: qodana-results/sarif/qodana.sarif.json
          checkout_path: ${{ github.workspace }}
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 6: Upload Qodana HTML report
      - name: Upload Qodana HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: qodana-html-report
          path: qodana-results/report

      # Step 7: Run UI and API Tests in Parallel
      - name: Run UI and API Tests
        run: |
          mvn clean test \
            -Dsurefire.parallel=classes \
            -Dsurefire.threadCount=10

      # Step 8: Upload Test HTML Reports
      - name: Upload Test HTML Reports
        uses: actions/upload-artifact@v3
        with:
          name: html-reports
          path: artifacts/reports/*.html

      # Step 9: Upload Screenshots
      - name: Upload Screenshots
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: artifacts/screenshots/*.png

      # Step 10: Upload API Artifacts
      - name: Upload API JSON Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: api-artifacts
          path: artifacts/api/*.json

      # Step 11: Optional - Call Analytics Endpoint
      - name: Refresh Analytics
        run: |
          curl -X POST https://jsonplaceholder.typicode.com/posts \
               -H "Content-Type: application/json" \
               -d '{"triggered_by": "github_actions"}'
