name: Full Regression Suite

on:
  push:
    branches:
      - master
  schedule:
    # Runs every night at 2:00 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  regression-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [17]

    steps:
      # Step 1: Checkout repository
      - uses: actions/checkout@v4

      # Step 2: Setup Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}

      # Step 3: Cache Maven packages
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Run UI and API Tests in parallel
      - name: Run UI and API Tests
        run: mvn clean test -Dsurefire.parallel=classes -Dsurefire.threadCount=10

      # Step 5: Upload HTML reports (if exist)
      - name: Upload HTML Reports
        if: always()
        run: |
          if compgen -G "artifacts/html/*.html" > /dev/null; then
            echo "HTML reports found, uploading..."
          else
            echo "No HTML reports found."
          fi
        uses: actions/upload-artifact@v4
        with:
          name: html-reports
          path: artifacts/html/*.html

      # Step 6: Upload screenshots (if exist)
      - name: Upload Screenshots
        if: always()
        run: |
          if compgen -G "artifacts/screenshots/*.png" > /dev/null; then
            echo "Screenshots found, uploading..."
          else
            echo "No screenshots found."
          fi
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: artifacts/screenshots/*.png

      # Step 7: Optional Analytics call (safe)
      - name: Refresh Analytics
        run: |
          echo "Calling analytics endpoint..."
          curl -X POST https://jsonplaceholder.typicode.com/posts \
               -H "Content-Type: application/json" \
               -d '{"triggered_by": "github_actions"}' || echo "Analytics call failed, continuing."
