#-------------------------------------------------------------------------------#
# Qodana Code Quality GitHub Actions Workflow
# Documentation: https://www.jetbrains.com/help/qodana/about-qodana.html
#-------------------------------------------------------------------------------#

name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Run Qodana scan
      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2025.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          pr-mode: false
          use-caches: true
          post-pr-comment: true
          use-annotations: true
          upload-result: true           # Upload reports as artifact
          push-fixes: 'none'
          output-path: qodana-results   # Path to store scan results

      # Step 3: Upload SARIF file for GitHub Code Scanning
      - name: Upload Qodana SARIF
        if: always()                  # Run even if previous step fails
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: qodana-results/sarif/qodana.sarif.json
          checkout_path: ${{ github.workspace }}
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Upload full Qodana HTML report as artifact
      - name: Upload Qodana HTML report
        uses: actions/upload-artifact@v3
        with:
          name: qodana-html-report
          path: qodana-results/report
