#-------------------------------------------------------------------------------#
#                  Qodana - JetBrains Code Quality Analysis                     #
#      Docs: https://www.jetbrains.com/help/qodana/github-integration.html      #
#-------------------------------------------------------------------------------#

name: Qodana Code Quality

on:
  workflow_dispatch:     # Manual trigger
  pull_request:          # On every PR
  push:                  # On every push to main branches
    branches:
      - master
      - main
  schedule:              # Optional: nightly scan
    - cron: "0 1 * * *"  # Runs every night at 01:00 UTC

jobs:
  qodana:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      checks: write
      security-events: write  # ✅ Needed for SARIF upload to GitHub Code Scanning

    steps:
      # ✅ Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ✅ Step 2: Set up Java (if Qodana needs it)
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # ✅ Step 3: Run Qodana scan
      - name: Run Qodana Code Quality Scan
        uses: JetBrains/qodana-action@v2025.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          pr-mode: true            # Analyze only changed files in PRs
          use-caches: true
          use-annotations: true
          post-pr-comment: true
          upload-result: true      # ✅ Upload SARIF results as artifacts
          push-fixes: 'none'       # Auto-fixes (requires Ultimate plan)

      # ✅ Step 4: Upload SARIF to GitHub Code Scanning
      - name: Upload SARIF results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: qodana.sarif.json
